### ISSUE TITLE
Failed:Could not parse query. SyntaxError: Unexpected token d

### ISSUE THREAD

**Issue by Maxwell101** [Imaginea/mViewer#177]
This is the error message I get when I type this in the Query Executor:

db.messages.findOne( { SEQNUM : "504444" } )

In fact, any command I type in returns a Failed error message.  I have another front end for mongodb with a built in executor and all my commands work.

What am I missing?

Thanks

**Comment by himukr** [comment]
please use the current version -v0.9.2 for performing such type of queries as 
mViewer-v0.9.1 support is limited to basic create/drop/update/insert/view documents.

steps for getting -v0.9.2 is mentioned in the README file.

**Comment by Maxwell101** [comment]
Thanks….but the only thing available for download @ github is 0.9.1 as far as I could tell.  Can you tell me where to get 0.9.2 beta?

Thanks

**Comment by Maxwell101** [comment]
I found the 0.9.2 download.  When I try to run it I get command not found.  The new startup file is “start_mviewer.sh” – the old one is “start_mViewer.sh” – note the capitol V.  The old one is the only one that will run.

**Comment by Maxwell101** [comment]
Will it be possible to search a collection for a specific keyword using the query executor?  All commands I type in come up with error messages.

**Comment by himukr** [comment]
thanks for pointing out the script issue...

can you put your command with error here?
For searching keyword please stick to below syntax:-
{ <field>: { $regex: 'pattern', $options: '<options>' } }

pattern within slash /<pattern>/ is not yet supported use $regex with "<pattern>" syntax instead

**Comment by himukr** [comment]
Reg your script issue , please make sure following:
1)copy winstone-0.9.10.jar from src/tools/winstone-0.9.10.jar to ./script 
2)create mViewer.war by either of two:
   i) ant dist
   ii) mvn clean package

3) copy mViewer.war to ./script depending upon:
   i) if "ant dist" used, copy   mViewer.war from ./staging/mViewer.jar
   ii) if "mvn clean package" used, copy mViewer.war from ./target/mViewer-0.9.2.war
       Make sure to rename mViewer-0.9.2.war to mViewer.war

4) change script permission : chmod +x start_mviewer.sh

5) execute script :   ./start_mviewer.sh 8080 
(make sure port is available)

**Comment by Maxwell101** [comment]
Command:  db.messages.findOne( { SEQNUM : "504444" } )

Error: Failed:Could not parse query. SyntaxError: Unexpected token d



Doesn’t matter what command I use, always comes back with an error.



Thanks

RIck

**Comment by himukr** [comment]
yes in v0.9.1 you can't run queries.
Try to download v0.9.2 and then follow the steps that i mentioned in previous comment..

**Comment by Maxwell101** [comment]
I did download 0.9.2.  It looks the same How do I tell what version I’m running?

**Comment by Maxwell101** [comment]
1)copy winstone-0.9.10.jar from src/tools/winstone-0.9.10.jar to ./script – Where is ./script located

I’m new to this stuff.  Can you give me a step by step for creating mViewer.war?

Thanks

**Comment by himukr** [comment]
for creating war file you just have to go inside mViewer folder and run "ant dist" (first install ant in your system by "sudo apt-get install ant")

**Comment by Maxwell101** [comment]
There’s already a mViewer.war file in the mviewer folder.

**Comment by Maxwell101** [comment]
This is what happens when I run ant dist:

ser@syslog:/var/mviewer$ ant dist
Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-7-openjdk-amd64/lib/tools.jar
Buildfile: /var/mviewer/build.xml

BUILD FAILED
Target "dist" does not exist in the project "null". 

Total time: 0 seconds

________________________________________

**Comment by aaruna** [comment]
Can you try with oracle jdk?

**Comment by Maxwell101** [comment]
I don’t know what that is

**Comment by aaruna** [comment]
You can try out the steps mentioned [here] (http://www.webupd8.org/2012/01/install-oracle-java-jdk-7-in-ubuntu-via.html)

**Comment by Maxwell101** [comment]
Do you know how to check which version of mViewer is running?

**Comment by himukr** [comment]
if you are running latest version (0.9.2) you can see the version details in first screen at the bottom right of the logo (previous version does not have any version detail)

**Comment by Maxwell101** [comment]
I don’t see any version #.  This must be the old one.

[cid:image003.jpg@01D0B3D5.B69071F0]

**Comment by Maxwell101** [comment]
I've got 0.9.2 running but when I click on the collection I get this:
 
Could not execute your request. Please check if server is running.

________________________________________
