### ISSUE TITLE
Keyword search

### ISSUE THREAD

**Issue by Maxwell101** [Imaginea/mViewer#181]
I can use this format: {"MESSAGES": "Core five"}  This will only return results if I match the whole string.  What's the syntax for searching messages for a keyword?  

I tried this format : { field: { $regex: 'pattern', $options: 'options' } } but it didn't work.

**Comment by himukr** [comment]
this support is added in latest version.
you are using 0.9.1 as i n 0.9.2 you have to write the complete query db.[your-collection-name].find({"MESSAGES": "Core five"})
